---
- name: Upgrade all packages
  dnf:
    name: "*"

- name: Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes

- name: Reboot required
  ansible.builtin.command: "/usr/bin/needs-restarting -r"
  register: reboot_required
  ignore_errors: True
#     changed_when: False
  failed_when: reboot_required.rc == 2
  when: doupgrade == "yes"